const {
    Accordion,
    AccordionActions,
    AccordionDetails,
    AccordionSummary,
    Alert,
    AlertTitle,
    AppBar,
    Autocomplete,
    Avatar,
    AvatarGroup,
    Backdrop,
    BackdropUnstyled,
    Badge,
    BadgeUnstyled,
    BottomNavigation,
    BottomNavigationAction,
    Box,
    Breadcrumbs,
    Button,
    ButtonBase,
    ButtonGroup,
    Card,
    CardActionArea,
    CardActions,
    CardContent,
    CardHeader,
    CardMedia,
    Checkbox,
    Chip,
    CircularProgress,
    ClickAwayListener,
    Collapse,
    Container,
    CssBaseline,
    Dialog,
    DialogActions,
    DialogContent,
    DialogContentText,
    DialogTitle,
    Divider,
    Drawer,
    Fab,
    Fade,
    FilledInput,
    FormControl,
    FormControlLabel,
    FormControlUnstyled,
    FormControlUnstyledContext,
    FormGroup,
    FormHelperText,
    FormLabel,
    FormLabelRoot,
    GlobalStyles,
    Grid,
    Grow,
    Hidden,
    Icon,
    IconButton,
    ImageList,
    ImageListItem,
    ImageListItemBar,
    Input,
    InputAdornment,
    InputBase,
    InputLabel,
    LinearProgress,
    Link,
    List,
    ListItem,
    ListItemAvatar,
    ListItemButton,
    ListItemIcon,
    ListItemSecondaryAction,
    ListItemText,
    ListSubheader,
    Menu,
    MenuItem,
    MenuList,
    MobileStepper,
    Modal,
    ModalManager,
    ModalUnstyled,
    NativeSelect,
    NoSsr,
    OutlinedInput,
    Pagination,
    PaginationItem,
    Paper,
    Popover,
    Popper,
    Portal,
    Radio,
    RadioGroup,
    Rating,
    ScopedCssBaseline,
    Select,
    Skeleton,
    Slide,
    Slider,
    SliderMark,
    SliderMarkLabel,
    SliderRail,
    SliderRoot,
    SliderThumb,
    SliderTrack,
    SliderUnstyled,
    SliderValueLabel,
    SliderValueLabelUnstyled,
    Snackbar,
    SnackbarContent,
    SpeedDial,
    SpeedDialAction,
    SpeedDialIcon,
    Stack,
    Step,
    StepButton,
    StepConnector,
    StepContent,
    StepIcon,
    StepLabel,
    Stepper,
    StyledEngineProvider,
    SvgIcon,
    SwipeableDrawer,
    Switch,
    SwitchUnstyled,
    Tab,
    TabScrollButton,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableFooter,
    TableHead,
    TablePagination,
    TableRow,
    TableSortLabel,
    Tabs,
    TextField,
    TextareaAutosize,
    ThemeProvider,
    ToggleButton,
    ToggleButtonGroup,
    Toolbar,
    Tooltip,
    Typography,
    Unstable_TrapFocus,
    Zoom,
    accordionActionsClasses,
    accordionClasses,
    accordionDetailsClasses,
    accordionSummaryClasses,
    adaptV4Theme,
    alertClasses,
    alertTitleClasses,
    alpha,
    appBarClasses,
    autocompleteClasses,
    avatarClasses,
    avatarGroupClasses,
    backdropClasses,
    backdropUnstyledClasses,
    badgeClasses,
    badgeUnstyledClasses,
    bottomNavigationActionClasses,
    bottomNavigationClasses,
    breadcrumbsClasses,
    buttonBaseClasses,
    buttonClasses,
    buttonGroupClasses,
    capitalize,
    cardActionAreaClasses,
    cardActionsClasses,
    cardClasses,
    cardContentClasses,
    cardHeaderClasses,
    cardMediaClasses,
    checkboxClasses,
    chipClasses,
    circularProgressClasses,
    collapseClasses,
    colors,
    containerClasses,
    createChainedFunction,
    createFilterOptions,
    createMuiTheme,
    createSvgIcon,
    createTheme,
    darkScrollbar,
    darken,
    debounce,
    decomposeColor,
    deprecatedPropType,
    dialogActionsClasses,
    dialogClasses,
    dialogContentClasses,
    dialogContentTextClasses,
    dialogTitleClasses,
    dividerClasses,
    drawerClasses,
    duration,
    easing,
    emphasize,
    experimentalStyled,
    fabClasses,
    filledInputClasses,
    formControlClasses,
    formControlLabelClasses,
    formControlUnstyledClasses,
    formGroupClasses,
    formHelperTextClasses,
    formLabelClasses,
    generateUtilityClass,
    generateUtilityClasses,
    getAccordionActionsUtilityClass,
    getAccordionDetailsUtilityClass,
    getAccordionSummaryUtilityClass,
    getAccordionUtilityClass,
    getAlertTitleUtilityClass,
    getAlertUtilityClass,
    getAppBarUtilityClass,
    getAutocompleteUtilityClass,
    getAvatarGroupUtilityClass,
    getAvatarUtilityClass,
    getBackdropUtilityClass,
    getBadgeUtilityClass,
    getBottomNavigationActionUtilityClass,
    getBottomNavigationUtilityClass,
    getBreadcrumbsUtilityClass,
    getButtonBaseUtilityClass,
    getButtonGroupUtilityClass,
    getButtonUtilityClass,
    getCardActionAreaUtilityClass,
    getCardActionsUtilityClass,
    getCardContentUtilityClass,
    getCardHeaderUtilityClass,
    getCardMediaUtilityClass,
    getCardUtilityClass,
    getCheckboxUtilityClass,
    getChipUtilityClass,
    getCircularProgressUtilityClass,
    getCollapseUtilityClass,
    getContainerUtilityClass,
    getContrastRatio,
    getDialogActionsUtilityClass,
    getDialogContentTextUtilityClass,
    getDialogContentUtilityClass,
    getDialogTitleUtilityClass,
    getDialogUtilityClass,
    getDividerUtilityClass,
    getDrawerUtilityClass,
    getFabUtilityClass,
    getFilledInputUtilityClass,
    getFormControlLabelUtilityClasses,
    getFormControlUnstyledUtilityClasses,
    getFormControlUtilityClasses,
    getFormGroupUtilityClass,
    getFormHelperTextUtilityClasses,
    getFormLabelUtilityClasses,
    getGridUtilityClass,
    getIconButtonUtilityClass,
    getIconUtilityClass,
    getImageListItemBarUtilityClass,
    getImageListItemUtilityClass,
    getImageListUtilityClass,
    getInputAdornmentUtilityClass,
    getInputBaseUtilityClass,
    getInputLabelUtilityClasses,
    getInputUtilityClass,
    getLinearProgressUtilityClass,
    getLinkUtilityClass,
    getListItemAvatarUtilityClass,
    getListItemButtonUtilityClass,
    getListItemIconUtilityClass,
    getListItemSecondaryActionClassesUtilityClass,
    getListItemTextUtilityClass,
    getListItemUtilityClass,
    getListSubheaderUtilityClass,
    getListUtilityClass,
    getLuminance,
    getMenuItemUtilityClass,
    getMenuUtilityClass,
    getMobileStepperUtilityClass,
    getModalUtilityClass,
    getNativeSelectUtilityClasses,
    getOutlinedInputUtilityClass,
    getPaginationItemUtilityClass,
    getPaginationUtilityClass,
    getPaperUtilityClass,
    getPopoverUtilityClass,
    getRadioUtilityClass,
    getRatingUtilityClass,
    getScopedCssBaselineUtilityClass,
    getSelectUtilityClasses,
    getSkeletonUtilityClass,
    getSliderUtilityClass,
    getSnackbarContentUtilityClass,
    getSnackbarUtilityClass,
    getSpeedDialActionUtilityClass,
    getSpeedDialIconUtilityClass,
    getSpeedDialUtilityClass,
    getStepButtonUtilityClass,
    getStepConnectorUtilityClass,
    getStepContentUtilityClass,
    getStepIconUtilityClass,
    getStepLabelUtilityClass,
    getStepUtilityClass,
    getStepperUtilityClass,
    getSvgIconUtilityClass,
    getSwitchUnstyledUtilityClass,
    getSwitchUtilityClass,
    getTabScrollButtonUtilityClass,
    getTabUtilityClass,
    getTableBodyUtilityClass,
    getTableCellUtilityClass,
    getTableContainerUtilityClass,
    getTableFooterUtilityClass,
    getTableHeadUtilityClass,
    getTablePaginationUtilityClass,
    getTableRowUtilityClass,
    getTableSortLabelUtilityClass,
    getTableUtilityClass,
    getTabsUtilityClass,
    getTextFieldUtilityClass,
    getToggleButtonGroupUtilityClass,
    getToggleButtonUtilityClass,
    getToolbarUtilityClass,
    getTooltipUtilityClass,
    getTouchRippleUtilityClass,
    getTypographyUtilityClass,
    gridClasses,
    hexToRgb,
    hslToRgb,
    iconButtonClasses,
    iconClasses,
    imageListClasses,
    imageListItemBarClasses,
    imageListItemClasses,
    inputAdornmentClasses,
    inputBaseClasses,
    inputClasses,
    inputLabelClasses,
    isHostComponent,
    isMuiElement,
    lighten,
    linearProgressClasses,
    linkClasses,
    listClasses,
    listItemAvatarClasses,
    listItemButtonClasses,
    listItemClasses,
    listItemIconClasses,
    listItemSecondaryActionClasses,
    listItemTextClasses,
    listSubheaderClasses,
    createStyles,
    menuClasses,
    menuItemClasses,
    mobileStepperClasses,
    modalClasses,
    modalUnstyledClasses,
    nativeSelectClasses,
    outlinedInputClasses,
    ownerDocument,
    ownerWindow,
    paginationClasses,
    paginationItemClasses,
    paperClasses,
    popoverClasses,
    radioClasses,
    ratingClasses,
    recomposeColor,
    requirePropFactory,
    responsiveFontSizes,
    rgbToHex,
    scopedCssBaselineClasses,
    selectClasses,
    setRef,
    skeletonClasses,
    sliderClasses,
    sliderUnstyledClasses,
    snackbarClasses,
    snackbarContentClasses,
    speedDialActionClasses,
    speedDialClasses,
    speedDialIconClasses,
    stepButtonClasses,
    stepClasses,
    stepConnectorClasses,
    stepContentClasses,
    stepIconClasses,
    stepLabelClasses,
    stepperClasses,
    styled,
    svgIconClasses,
    switchClasses,
    switchUnstyledClasses,
    tabClasses,
    tabScrollButtonClasses,
    tableBodyClasses,
    tableCellClasses,
    tableClasses,
    tableContainerClasses,
    tableFooterClasses,
    tableHeadClasses,
    tablePaginationClasses,
    tableRowClasses,
    tableSortLabelClasses,
    tabsClasses,
    textFieldClasses,
    toggleButtonClasses,
    toggleButtonGroupClasses,
    toolbarClasses,
    tooltipClasses,
    touchRippleClasses,
    typographyClasses,
    unstable_composeClasses,
    unstable_createMuiStrictModeTheme,
    unstable_getUnit,
    unstable_toUnitless,
    unstable_useEnhancedEffect,
    unstable_useId,
    unsupportedProp,
    useAutocomplete,
    useControlled,
    useEventCallback,
    useForkRef,
    useFormControl,
    useFormControlUnstyled,
    useIsFocusVisible,
    useMediaQuery,
    usePagination,
    useRadioGroup,
    useScrollTrigger,
    useSwitch,
    useTheme,
    useThemeProps,
    withStyles,
    withTheme,
} = MaterialUI;

// const DefaultStyle = makeStyles({
//     root: {
//         background: "linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)",
//         border: 0,
//         borderRadius: 3,
//         boxShadow: "0 3px 10px 1px rgb(255, 105, 135)",
//         color: "white",
//         height: 48,
//         padding: "10px 30px",
//     },
//     sub: {
//         background: "linear-gradient(-45deg, #FE6B8B 30%, #FF8E53 90%)",
//     },
// });

const ListStyle = styled('div')({
    color: 'white',
    background: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
    padding: '10px 10px',
    borderRadius: 10,
    width: 'max-content',
});
const ListTitle = styled('h1')({
    color: 'black',
    background: 'white',
    padding: 10,
    borderRadius: 10,
    textAlign: 'center',
    boxShadow: "0px 0px 10px 1px black"
});
const ButtonGroupingButton = styled(Button)(({ theme }) => ({
    color: 'black',
    background: 'linear-gradient(114deg, rgba(0,212,255,1) 0%, rgba(36,247,217,1) 100%)',
    borderRadius: 10,
    boxShadow: "0px 0px 10px 1px black",
    width: '100%',
}));

function App() {
    return (
        <ListStyle>
            <ListTitle>WDw</ListTitle>
            <AddMenuButton text="wdddddddddddddddddddddda" />
            <AddMenuButton text="wdddddddddddddddddddddda" />
            <AddMenuButton text="wdw" />
            <AddMenuButton text="啊？" />
            <FormControl fullWidth>
                <InputLabel>Age</InputLabel>
                    <Select
                        value={10}
                        label="Age"
                    >
                    <MenuItem value={10}>Ten</MenuItem>
                    <MenuItem value={20}>Twenty</MenuItem>
                    <MenuItem value={30}>Thirty</MenuItem>
                </Select>
            </FormControl>
        </ListStyle>
    );
}

function AddMenuButton(content) {
    return (
        <Box>
            <ButtonGroupingButton variant="contained">{content.text}</ButtonGroupingButton>
            <br/>
        </Box>
    )
}

ReactDOM.render(
    <App />,
    document.querySelector("#root")
);
